### ISSUE TITLE
Can is it possible to disable threshold 

### ISSUE THREAD

**Issue by Ashutosh2** [srph/angular-infinite-scroll#1]
In my app, on scrolling with threshold set to 200, making two same web service call, one is because of threshold is set to 200 and other is reaching at bottom, So is there is any way to disable threshold, or any alternate way to avoid this situation.

Thanks in advance.

**Comment by srph** [comment]
I'm not sure if I correctly understood your question. Maybe try setting `threshold` to `0`?

**Comment by Ashutosh2** [comment]
Yes, I tried that, but still calling web call twice. I think because the threshold's default value set to 200?
What happening is, when I scrolled down, before I reached the end, the making web call, and If I continue to scroll upto end of list, that same time it also calling a web call.

Anyways. Thanks for quick replay.

**Comment by srph** [comment]
I just ate some dinner, sorry about that :smile: 

---

I see, is that web call asynchronous (`$http`)? If so, you should return a promise as documented.

``` html
<div srph-infinite-scroll="callback()"
  {disabled="true"}
  {container="true"}
  {throttle="0"}
  {threshold="200"}>
  <!-- your ng-repeat, typically -->
  <div ng-repeat="apple in apples"> {{ apple.name }} </div>
</div>
```

``` js
app.controller('MainController', function($http, $scope) {
  $scope.callback = function() {
    return $http.get('..');
  }
});
```

Don't forget to `return` the `promise` (`$http` returns a `promise`). Otherwise, the web call will keep getting called each time you scroll.

**Comment by Ashutosh2** [comment]
Haha... :)
Thanks for quick reply. I'll certainly try that.

Again Thank you very much for your time.
This modules working like a charm!!!
Thanks again.

**Comment by srph** [comment]
I hope it works for you. If it doesn't, feel free to re-open the issue.
